// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACol: typeof import('ant-design-vue/es')['Col']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    AssetMetadata: typeof import('./src/components/AssetMetadata.vue')['default']
    AssetsTable: typeof import('./src/components/AssetsTable.vue')['default']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATag: typeof import('ant-design-vue/es')['Tag']
    CatalogOverview: typeof import('./src/components/CatalogOverview.vue')['default']
    CollectionItems: typeof import('./src/components/CollectionItems.vue')['default']
    CollectionMetadata: typeof import('./src/components/CollectionMetadata.vue')['default']
    CollectionOverview: typeof import('./src/components/CollectionOverview.vue')['default']
    Item: typeof import('./src/components/Item.vue')['default']
    ItemLinks: typeof import('./src/components/ItemLinks.vue')['default']
    ItemMetadata: typeof import('./src/components/ItemMetadata.vue')['default']
    ItemsFilter: typeof import('./src/components/ItemsFilter.vue')['default']
    LeafletMap: typeof import('./src/components/LeafletMap.vue')['default']
    ListCatalogs: typeof import('./src/components/ListCatalogs.vue')['default']
    ListCollections: typeof import('./src/components/ListCollections.vue')['default']
    ListItems: typeof import('./src/components/ListItems.vue')['default']
    MapAlert: typeof import('./src/components/MapAlert.vue')['default']
    MetadataTables: typeof import('./src/components/Base/MetadataTables.vue')['default']
    Providers: typeof import('./src/components/Providers.vue')['default']
    QueryableInput: typeof import('./src/components/QueryableInput.vue')['default']
    ShareAndSource: typeof import('./src/components/ShareAndSource.vue')['default']
    SimpleListFilter: typeof import('./src/components/Base/SimpleListFilter.vue')['default']
  }
}

export { }
